-- local cmp = require('cmp')
--
-- cmp.setup {
--   snippet = {
--     expand = function(args)
--       require('luasnip').lsp_expand(args.body)
--     end,
--   },
--   window = {
--     documentation = cmp.config.window.bordered(),
--   },
--   completion = {
--     completeopt = 'menu,menuone,preview,noselect',
--   },
--   mapping = cmp.mapping.preset.insert {
--     ['<C-Space>'] = cmp.mapping.complete(),
--     ['<Tab>'] = cmp.mapping.confirm { select = true },
--   },
--
--   sources = cmp.config.sources({
--     { name = 'copilot' },
--     { name = 'nvim_lsp' },
--     { name = 'nvim_lua' },
--     { name = 'buffer' },
--     { name = 'path' },
--   }, { name = 'buffer' }),
-- }
